# Generated by Django 2.2.1 on 2019-05-25 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import extraapps.DjangoUeditor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_info', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('img', models.ImageField(upload_to='banner/', verbose_name='轮播图片')),
                ('link_url', models.URLField(max_length=100, verbose_name='图片链接')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否可用')),
            ],
            options={
                'verbose_name': '轮播图表',
                'verbose_name_plural': '轮播图表',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='分类编码')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('index', models.IntegerField(default=999, verbose_name='排序')),
            ],
            options={
                'verbose_name': '文章分类字典表',
                'verbose_name_plural': '文章分类字典表',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='链接名称')),
                ('link_url', models.URLField(max_length=100, verbose_name='网址')),
            ],
            options={
                'verbose_name': '友情链接表',
                'verbose_name_plural': '友情链接表',
            },
        ),
        migrations.CreateModel(
            name='Recom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='推荐位编码')),
                ('name', models.CharField(max_length=20, verbose_name='推荐位')),
            ],
            options={
                'verbose_name': '推荐位字典表',
                'verbose_name_plural': '推荐位字典表',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='标签编码')),
                ('name', models.CharField(max_length=20, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '标签字典表',
                'verbose_name_plural': '标签字典表',
            },
        ),
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('img', models.ImageField(blank=True, null=True, upload_to='artical-img/%Y-%m', verbose_name='文章图片')),
                ('excerpt', models.CharField(blank=True, default='[暂未提供摘要]', max_length=100, null=True, verbose_name='摘要')),
                ('body', extraapps.DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='内容')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modi_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blogapp.Category', verbose_name='分类id')),
                ('recom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blogapp.Recom', verbose_name='推荐位id')),
                ('tags', models.ManyToManyField(blank=True, to='blogapp.Tag', verbose_name='标签id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者id')),
            ],
            options={
                'verbose_name': '博客文章表',
                'verbose_name_plural': '博客文章表',
            },
        ),
    ]
