# Generated by Django 2.2.1 on 2019-05-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20190525_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='excerpt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='摘要'),
        ),
    ]
